version: '3'

services:
  pizza-database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  pizzabackend:
    build:
      context: ./PizzaBackend
      dockerfile: Dockerfile    
    restart: always
    ports:
      - 5000:5000
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://pizza-database:27017/
      - DB_URL=mongodb://pizza-database
    depends_on:
      - pizza-database

  pizzafrontend:
    build:
      context: ./Pizzafrontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80 # 4200:4200
    environment:
      - PORT=5000
      - SERVER_URL=http://192.168.0.166:5000 # Should be matched with your current IP or Domain
  