version: '3'

services:
  pizza-database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  pizzabackend:
    image: pizzabackend
    restart: always
    ports:
      - 5000:5000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://pizza-database:27017/
  pizzafrontend:
    image: pizzafrontend
    restart: always
    ports:
      - 4200:4200
  