apiVersion: v1
kind: Service
metadata:
  name: pizzaappbackend-service
  namespace: junction
spec:
  selector:
    app: pizzaappbackend
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: pizzabackend
  type: ClusterIP