name: Pizza App
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest #self-hosted
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker-compose up
      - run: docker-compose down
      
        
